### ISSUE TITLE
Empty browser window, error in dev console

### ISSUE THREAD

**Issue by p3k** [YunoHost-Apps/strut_ynh#3]
Installation of Strut on an Odroid C1 w/ fresh Jessie/YH config seems to be fine but when I open the app in the browser the window remains empty.

In the developer console I can see the following error:
```
Uncaught SyntaxError: Unexpected identifier
    at amd-app.js:11
    at amd-app.js:12
    at amd-app.js:21
```

**Comment by p3k** [comment]
Bump (issue still persists in YH 2.7.2)

**Comment by alexAubin** [comment]
Random question here (I have no knowledge about this app or Odroid :/) but do you reproduce the issue with any browser ?

**Comment by p3k** [comment]
you are right, @alexAubin – the error does not occur when i open the strut app in firefox. (so far for a work-around.)

**Comment by p3k** [comment]
…aaaaand it also works in an incognito window (chrome) – so i assume something is going on between strut and one of the installed extensions.

good enough for me to close this issue. thanks again, @alexAubin
